import 'jquery'
import  'popper.js'

import './sass/main.sass'
import './js/standard-buttons/__button'
import './js/pie-chart/__doughnut'
import './js/pie-chart/__percentages'
import './js/sliders/slider_valued'
import './js/sliders/slider_tracked'
import './js/stages/stages'